require("papi.keymaps")
require("papi.options")
require("papi.plugins")
require("papi.colorscheme")
require("papi.colorizer")
require("papi.cmp")
require("papi.lsp")
require("papi.telescope")
require("papi.treesitter")
require("papi.autopairs")

