require("papi.keymaps")
require("papi.options")
require("papi.plugins")
require("papi.colorscheme")
require("papi.colorizer")
require("papi.cmp")
require("papi.lsp")
require("papi.telescope")
require("papi.treesitter")
require("papi.autopairs")
require("papi.surround")
require("papi.comments")
require("papi.gitsigns")
require("papi.nvim_tree")
require("papi.bufferline")
require("papi.lualine")

